import type { Metadata } from "next";
import { Manrope, Sora } from "next/font/google";
import "./globals.css";
import { Providers } from "@/providers";


const appHeading = Sora({
  variable: "--font-app-heading",
  subsets: ["latin"],
});

const appUi = Manrope({
  variable: "--font-app-ui",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${appHeading.variable} ${appUi.variable} antialiased`}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
